---
   
   - name: Install Keystone
     hosts: client_one
     vars_files: 
       - ../group_vars/all
       - ../group_vars/keystone
     sudo: yes
     roles: 
       - { role: ../roles/keystone }

